<?php

return [
    'admin' => [
        [
            'title'       => 'Company list',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'general',
            'handler'     => 'list',
            'permissions' => 'admin-company-list',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company add',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'general',
            'handler'     => 'add',
            'permissions' => 'admin-company-add',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company update',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'general',
            'handler'     => 'update',
            'permissions' => 'admin-company-update',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company update time and status',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'general',
            'handler'     => 'package',
            'permissions' => 'admin-company-time-status',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company report',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'general',
            'handler'     => 'package',
            'permissions' => 'admin-company-report',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company package add',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'package',
            'handler'     => 'add',
            'permissions' => 'admin-company-package-add',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company package update',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'package',
            'handler'     => 'update',
            'permissions' => 'admin-company-package-update',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company package list',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'package',
            'handler'     => 'list',
            'permissions' => 'admin-company-package-list',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company member list',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'member',
            'handler'     => 'list',
            'permissions' => 'admin-company-member-list',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company member add',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'member',
            'handler'     => 'add',
            'permissions' => 'admin-company-member-add',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company member update',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'member',
            'handler'     => 'update',
            'permissions' => 'admin-company-member-update',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company member view',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'member',
            'handler'     => 'view',
            'permissions' => 'admin-company-member-view',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company team list',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'team',
            'handler'     => 'list',
            'permissions' => 'admin-company-team-list',
            'role'        => [
                'admin',
            ],
        ],
        [
            'title'       => 'Company team member list',
            'module'      => 'company',
            'section'     => 'admin',
            'package'     => 'team-member',
            'handler'     => 'list',
            'permissions' => 'admin-company-team-member-list',
            'role'        => [
                'admin',
            ],
        ],
    ],
    'api'   => [
        [
            'title'       => 'Company member list',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'member',
            'handler'     => 'list',
            'permissions' => 'company-access',
            'role'        => [
                'member',
            ],
        ],
        [
            'title'       => 'Company member add',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'member',
            'handler'     => 'add',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company member view',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'member',
            'handler'     => 'view',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company member update',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'member',
            'handler'     => 'update',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company member role',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'member',
            'handler'     => 'role',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company profile view',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'profile',
            'handler'     => 'view',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company profile update',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'profile',
            'handler'     => 'update',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company package current',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'package',
            'handler'     => 'current',
            'permissions' => 'company-access',
            'role'        => [
                'member',
            ],
        ],
        [
            'title'       => 'Company package list',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'package',
            'handler'     => 'list',
            'permissions' => 'company-access',
            'role'        => [
                'member',
            ],
        ],
        [
            'title'       => 'Company team list',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team',
            'handler'     => 'list',
            'permissions' => 'company-access',
            'role'        => [
                'member',
            ],
        ],
        [
            'title'       => 'Company team add',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team',
            'handler'     => 'add',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company team update',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team',
            'handler'     => 'update',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company team member list',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team-member',
            'handler'     => 'list',
            'permissions' => 'company-access',
            'role'        => [
                'member',
            ],
        ],
        [
            'title'       => 'Company team member add',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team-member',
            'handler'     => 'add',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company team member update',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team-member',
            'handler'     => 'update',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],
        [
            'title'       => 'Company team member delete',
            'module'      => 'company',
            'section'     => 'api',
            'package'     => 'team-member',
            'handler'     => 'delete',
            'permissions' => 'company-manage',
            'role'        => [
                'companyadmin',
                'companygovernancemanager',
            ],
        ],


    ],
];